spring.application.name=Bus Reservation System
spring.data.mongodb.host = localhost
spring.data.mongodb.port = 27017
spring.data.mongodb.database = BuskarroData
#spring.data.mongodb.username = myusername
spring.data.mongodb.password = password
spring.security.user.name = Ashad
spring.security.user.password = Senku097
server.port=9090
spring.data.mongodb.auto-index-creation = true

jwt.secret=${JWT_SECRET}